### ISSUE TITLE
Kommentarnamen eigener Kommentare anpassen

### ISSUE THREAD

**Issue by matthias-reis** [matthias-reis/cardatheme#10]
Bei einigen Kommentaren von mir steht als Autor noch „Anne Reko“ oder sogar „cardamonchai“ oder „cardamon82“ Kann man das automatisiert irgendwie bei allen auf „Anne Reis“ anpassen? Das wäre genialst!

**Comment by matthias-reis** [comment]
Hast Du hier ein zwei Beispielseiten?

**Comment by cardamonchai** [comment]
Hallo Matze,
hier sind die Kommentare unter "cardamon82"
http://cardamonchai.com/wp-admin/edit-comments.php?s=cardamon82&comment_status=all&pagegen_timestamp=2015-05-10+13%3A38%3A20&_total=1050&_per_page=20&_page=1&_ajax_fetch_list_nonce=b8c7f76420&action=-1&comment_type&paged=1&action2=-1
und hier sind die Kommentare unter "Anne Reko"
http://cardamonchai.com/wp-admin/edit-comments.php?s=Anne+Reko&comment_status=all&pagegen_timestamp=2015-05-10+13%3A38%3A29&_total=63&_per_page=20&_page=1&paged=1&_ajax_fetch_list_nonce=b8c7f76420&action=-1&comment_type&action2=-1

**Comment by matthias-reis** [comment]
Wird nicht geloest ...
