### ISSUE TITLE
Einführung von Dachzeilen

### ISSUE THREAD

**Issue by cardamonchai** [matthias-reis/cardatheme#22]
Ich würde gerne Dachzeilen (Hauptkategorien) einführen, die in der Übersicht der Artikel (Startseite und Unterseiten) und auf der Seite selbst angezeigt werden. Diese sollen lauten:

- Fotostrecke
- Gedicht
- Werbung
- ...

Weitere überlege ich mir noch.

**Comment by matthias-reis** [comment]
Dublette
