### ISSUE TITLE
Beitragstypen

### ISSUE THREAD

**Issue by cardamonchai** [matthias-reis/cardatheme#25]
Neben den schon vorhandenen Beitragstypen "Artikel" und "Galerie" wären weitere schön. Hier würde ich zwischen zwei verschiedenen Beitragstypen-Typen unterscheiden:

- Fest angelegte (z. B. "Gedicht" immer nach einem bestimmten Styling) und
- ~~Selbst benennbar (dann möchte ich einfach ein bestimmtes Wort reinschreiben können wie zum Beispiel "Interview", "Reisebericht", "vegan" oder what ever)~~ (Erledigt)

**Comment by matthias-reis** [comment]
Wie es momentan angelet ist, wird je nach Beitragstyp (also dem Layout des Beitrags unterschieden) Alternativ kann man das aber auch mit einem eigenen Eingabefeld bewerkstelligen.

**Comment by matthias-reis** [comment]
- Artikel (schwarz auf weiss)
- Galerie (dunkelgrau, text an beliebiger Stelle)
- Galerie rechts (links der Text, rechts die Bilder - linksbündig)
- Gedicht (links Text, rechts ein einzelnes Bild, Artikelbild)
