### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by cardamonchai** [matthias-reis/cardatheme#28]
@matthias-reis Würdest Du persönlich an den Fonts nochmal etwas ändern?

**Comment by matthias-reis** [comment]
Ja. Soll auch der Ueberschriftenfont angepasst werden?

**Comment by cardamonchai** [comment]
@matthias-reis Ich fand Deine Ideen gestern auf jeden Fall schon mal gut. Ich notiere jetzt mal hier alle Schriftarten, die Du mir gezeigt hast, damit wir die nicht vergessen:

1. Open Sans Condensed
2. Amatic SC
3. Roboto Sans und mit
4. Merrieweather Serif (Italic auch sehr schön)
