### ISSUE TITLE
Disqus einbauen

### ISSUE THREAD

**Issue by matthias-reis** [matthias-reis/cardatheme#35]
Kommentare und Communityverwaltung fortan mit disqus.

- statt der Wordpress Kommentare
- bestehende Kommentare muessen bleiben
- bestehendes Kommentarfeld fortan ueber disqus
- optik zu 100% angleichen. Kommentare koennen sowohl von wordpress als auch asynchron von disqus kommen
- Kommentare solle enerst dann angezeigt werden, wenn disqus geantwortet hat 

- Kommentarfeld sollte oberhalb der bisherigen Vorschlaege angezeigt werden
- Like Option soll eingebunden werden.

**Comment by cardamonchai** [comment]
@matthias-reis Den kannst Du schließen.
